replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/emitter
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config:
  ACCOUNTS_RPC_ADDR: accounts.console.svc.cluster.local:5001

service:
  ports:
    grpc: 5003

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-emitter"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/emitter/config"
  vault.hashicorp.com/agent-inject-secret-sa-managers: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/emitter/sa_managers"
  vault.hashicorp.com/agent-inject-secret-sa-validators: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/emitter/sa_validators"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/dev-videocoin-network/console-dev-videocoin-network/emitter/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}='{{ $v }}'
    {{ end }}{{ end }}
